service:
  name: "osf-serverless-todo"

plugins:
  - serverless-webpack
  # - serverless-dynamodb-local
  - serverless-offline

useDotenv: true

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true # Creates DynamoDB in memory instance for local development
      migrate: true # Creates table if they were not created yet

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
    - Effect: Allow
      Action:
        - "ses:*"
      Resource:
        - "*"

functions:
  createTodo:
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /todos/{userId}
          method: POST
          cors: true

  createTodoCron:
    handler: src/functions/createTodoCron.handle
    events:
      # - schedule: rate(1 minute)

  getTodos:
    handler: src/functions/getTodos.handle
    events:
      - http:
          path: /todos/{userId}
          method: GET
          cors: true
resources:
  Resources:
    dbTodos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: todos

        # How many operations per second it supports
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

        # On DynamoDB we just declare the "column" that will be the ID/KEY
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
